# https://docs.travis-ci.com/user/languages/python/

#sudo: false
#language: python
#python:
#  - "3.7"
#cache: pip
#install:
#  - pip install -r requirements.txt

# script: python -m pytest --cov=src/

# https://docs.travis-ci.com/user/docker/
# https://docs.travis-ci.com/user/build-stages/share-docker-image/

sudo: true
dist: trusty

services:
  - docker
  
#before_deploy:
#    - docker build -t hbstarjason/k8s-deployment-example-app:$TRAVIS_TAG .
#deploy:
#    provider: script
#    script: docker.sh
#    on:
#        tags: true
script: 
  - git clone https://github.com/hbstarjason/k8s-deployment-example-app
  - cd k8s-deployment-example-app

# IMAGE_TAG=v1
# IMAGE_TAG=version2
env: 
  - IMAGE_TAG=version2
  
jobs:
  include:
    - stage: build docker image and push image
      script:
      - docker info
      - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
      - docker build -t k8s-deployment-example-app .
      - docker images
      - docker tag k8s-deployment-example-app $DOCKER_USERNAME/k8s-deployment-example-app:$IMAGE_TAG
      - docker push $DOCKER_USERNAME/k8s-deployment-example-app:$IMAGE_TAG
    - stage: test
      # script: docker run --rm $DOCKER_USERNAME/k8s-deployment-example-app:$IMAGE_TAG
      script: docker run --rm -p 5000:5000 $DOCKER_USERNAME/k8s-deployment-example-app:$IMAGE_TAG
    #- script: docker run --rm $DOCKER_USERNAME/k8s-deployment-example-app:$IMAGE_TAG | grep label
    - script: curl -s localhost:5000 | grep label
