# https://docs.travis-ci.com/user/languages/python/

sudo: false
language: python
#python:
#  - "3.7"
cache: pip
install:
  - pip install -r requirements.txt
  
services:
  - docker

# script: python -m pytest --cov=src/
before_deploy:
    - docker build -t hbstarjason/k8s-deployment-example-app:$TRAVIS_TAG .
deploy:
    provider: script
    script: docker.sh
    on:
        tags: true
