# https://docs.travis-ci.com/user/languages/python/

#sudo: false
#language: python
#python:
#  - "3.7"
#cache: pip
#install:
#  - pip install -r requirements.txt

# script: python -m pytest --cov=src/

# https://docs.travis-ci.com/user/docker/
# https://docs.travis-ci.com/user/build-stages/share-docker-image/

sudo: true
dist: trusty

services:
  - docker
  
#before_deploy:
#    - docker build -t hbstarjason/k8s-deployment-example-app:$TRAVIS_TAG .
#deploy:
#    provider: script
#    script: docker.sh
#    on:
#        tags: true
jobs:
  include:
    - stage: build docker image and push image
      script:
      - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
      - docker build -t Dockerfile .
      - docker images
      - docker tag k8s-deployment-example-app $DOCKER_USERNAME/k8s-deployment-example-app
      - docker push $DOCKER_USERNAME/k8s-deployment-example-app
    #- stage: test
    #  script: docker run --rm $DOCKER_USERNAME/travis-ci-build-stages-demo cat hello.txt
    #- script: docker run --rm $DOCKER_USERNAME/travis-ci-build-stages-demo cat hello.txt
