apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  replicas: 10
  selector:
    matchLabels:
      id: app
      type: main
  template:
    metadata:
      labels:
        id: app
        type: main
    spec:
      containers:
      - image: hbstarjason/k8s-deployment-example-app:v1
        imagePullPolicy: Always
        name: app
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
