name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    #runs-on: ubuntu-latest
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag k8s-deployment-example-app:$(date +%s)
